# Generated by Django 5.0.1 on 2024-02-17 08:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_comments', to='webapp.postneighbors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
