# Generated by Django 5.0.1 on 2024-02-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_neighborcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postneighbors',
            name='image',
            field=models.ImageField(default='../../../media/posts/default.webp', upload_to='posts/'),
        ),
    ]
