# Generated by Django 5.0.1 on 2024-02-10 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_update_at_post_updated_at_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
