# Generated by Django 5.0.1 on 2024-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_postneighbors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postneighbors',
            name='image',
            field=models.ImageField(default='../../media/posts/default.webp', upload_to='posts/'),
        ),
    ]
