# Generated by Django 5.0.1 on 2024-02-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_advertisement_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
