# Generated by Django 5.0.1 on 2024-02-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
