# Generated by Django 5.0.2 on 2024-02-14 05:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_post_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
