# Generated by Django 5.0.1 on 2024-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_business_alter_post_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(blank=True, choices=[('stores', 'Продуктовые магазины'), ('restaurants', 'Рестораны'), ('drug_stores', 'Аптеки')], max_length=255, null=True),
        ),
    ]
