# Generated by Django 5.0.1 on 2024-02-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_business_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(blank=True, choices=[('drugs', 'drugs'), ('restaurants', 'restaurants'), ('stores', 'stores'), ('clothing_stores', 'Магазины одежды'), ('beauty_salons', 'Салоны красоты'), ('auto_services', 'Автосервисы'), ('banks', 'Банки'), ('home_improvement', 'Универсальный дом'), ('fitness_centers', 'Фитнес-центры'), ('educational_institutions', 'Образовательные учреждения'), ('travel_agencies', 'Турагентства'), ('dry_cleaners', 'Химчистки'), ('clinics', 'Клиники')], max_length=255, null=True),
        ),
    ]
