# Generated by Django 5.0.2 on 2024-02-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_post_full_text'),
        ('webapp', '0016_alter_business_category'),
    ]

    operations = [
    ]
