# Generated by Django 5.0.1 on 2024-02-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_business_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='webapp.post')),
                ('n_post_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('webapp.post',),
        ),
    ]
