# Generated by Django 5.0.1 on 2024-02-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_neighborpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborpost',
            name='post_ptr',
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='post',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_post', to='webapp.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
