# Generated by Django 5.0.1 on 2024-02-16 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_user_profile_pic_postneighbors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postneighbors',
            old_name='local_post_id',
            new_name='n_post_id',
        ),
        migrations.AlterField(
            model_name='postneighbors',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
